MVC5.APP.WEB/Controllers/Clientes/ClienteController.cs
using MVC5.APP.APPLICATION.Clientes.DTO;
using MVC5.APP.APPLICATION.Clientes.Services.Interfaces;
using MVC5.APP.DOMAIN.Clientes.Services.Interfaces;
using System.Web;
using System.Web.Mvc;

namespace MVC5.APP.WEB.Controllers.Clientes
{
    public class ClienteController : Controller 
    {
        private readonly IClienteAppServices _clienteAppServices;

        public ClienteController(IClienteAppServices clienteAppServices)
        {
            _clienteAppServices = clienteAppServices;
        }

        public ActionResult Index()
        {
            var response = this._clienteAppServices.ListarClientes();
            return View(response);
        }

        public ActionResult Cadastro() 
        {
            return View();
        }

        public ActionResult GetListaClientes()
        {
            var response = this._clienteAppServices.ListarClientes();
            Response.StatusCode = 202;
            Response.Headers["X-Custom-Header"] = "UmValorNoHeader";
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CadastrarCliente(ClienteCadastrarRequest request) 
        {
            ClienteResponse  response =this._clienteAppServices.CadastrarCliente(request);
            Response.StatusCode = 204;
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }  
        
}

MVC5.APP.WEB/Controllers/HomeController.cs
using MVC5.APP.DOMAIN.Pedidos.Services.Interfaces;
using System.Web.Mvc;

namespace MVC5.APP.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPedidoService _pedidoService;


        public HomeController(IPedidoService pedidoService)
        {
            this._pedidoService = pedidoService;
        }

        public ActionResult Index()
        {
            var retorno = _pedidoService.BuscarTodosPedidos();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC5.APP.WEB/Controllers/Produtos/ProdutoController.cs
using MVC5.APP.APPLICATION.Produtos.DTO;
using MVC5.APP.APPLICATION.Produtos.Services.Interfaces;
using System.Web.Mvc;

namespace MVC5.APP.WEB.Controllers.Produtos
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoAppService _produtoAppService;

        public ProdutoController(IProdutoAppService produtoAppService)
        {
            this._produtoAppService = produtoAppService;
        }

      
        // GET: Produto
        public ActionResult Index()
        {
            var response = this._produtoAppService.RecuperarListaProdutos();
            return View(response);
        }

        public ActionResult Cadastro()
        {
            return View();
        }

        public ActionResult GetListaProdutos()
        {
            var response = this._produtoAppService.RecuperarListaProdutos();
            Response.StatusCode = 202; // Accepted
            Response.Headers["X-Custom-Header"] = "UmValorNoHeader";
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CadastrarProduto(ProdutoCadastrarRequest request)
        {
            ProdutoResponse response = this._produtoAppService.CadastrarProduto(request);
            Response.StatusCode = 204; // Sucesso e Algo foi Criado
            return Json(response, JsonRequestBehavior.AllowGet);

        }

    }
}

MVC5.APP.WEB/Views/Clientes/Cadastro.cshtml
@model MVC5.APP.APPLICATION.Clientes.DTO.ClienteCadastrarRequest
@{
    ViewBag.Title = "Cadastrar Novo Item";
}

<h2>View</h2>

@using (Html.BeginForm())
  {
    @Html.AntiForgeryToken()

    var fromField = Model;

    <div class="form-horizontal">
        <h4>Cadastrar Novo Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger"} )

        <div class="form-group">
           @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" } )
               <div class="col-md-10">
            @Html.LabelFor(model => model.Cpf, new { htmlAttributes: new { @class = "form-control" } } )
            @Html.LabelFor(model => model.Cpf, "", new { @class = "text-danger" })
               </div>
          </div>
            
        <div class="form-group">
           @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" } )
                <div class="col-md-10">
                    @Html.LabelFor(model => model.Nome, new { htmlAttributes : new { @class = "form-control" } } )
                    @Html.LabelFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>
            
        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2"} )
            <div class="col-md-10">
                @Html.LabelFor(model => model.Endereco, new {htmlAttributes: new { @class = "form-control"} } )
                @Html.LabelFor(model => model.Endereco, "", new { @class = "text-danger"})
            </div>
            </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="ChamarBackEnd" class="btn btn-default btn-outline-success my-lg-4" onclick="SalvarCliente()" />
            </div>
        </div>
    </div>
  }

<div>
    @Html.ActionLink("Back to list", "Index")
</div>

MVC5.APP.WEB/Views/Clientes/Index.cshtml
@model List<MVC5.APP.APPLICATION.Clientes.DTO.ClienteResponse>
@{
    ViewBag.Title = "Index";
}

<h2>View</h2>

<div class="row>

    <div class="col-10">Registrar Novo Cliente</div>
    <div class="col-2">
        @Html.ActionLink("Register New", "Cadastro", "Cliente", new { area = "" }, new { @class = "nav-link btn btn-info"})
    </div>

     <table class="table">
         <thead>
             <tr>
                 <th>Cpf</th>
                 <th>Nome</th>
                 <th>Endereco</th>
             </tr>
         </thead>
         <tbody>
             @foreach(var cliente in Model)
            {
                <tr>
                 <td>@cliente.Cpf</td>
                 <td>@cliente.Nome</td>
                <td>@cliente.Endereco</td>
                </tr>
            }
         </tbody>
     </table>

</div>

MVC5.APP.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

MVC5.APP.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

MVC5.APP.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

MVC5.APP.WEB/Views/Produto/Cadastro.cshtml
@model MVC5.APP.APPLICATION.Produtos.DTO.ProdutoCadastrarRequest

@{
    ViewBag.Title = "Cadastro Novo Produto";
}

<h2>View</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    var formField = Model;

    <div class="form-horizontal">
        <h4>Cadastro Novo Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SKU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fabricante, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fabricante, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fabricante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="ChamarBackEnd" class="btn btn-default btn-outline-success my-lg-4" onclick="SalvarProduto()" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC5.APP.WEB/Views/Produto/Index.cshtml
@model List<MVC5.APP.APPLICATION.Produtos.DTO.ProdutoResponse>
@{
    ViewBag.Title = "Produtos";
}

<h2>Index</h2>

<div class="row">

    <div class="col-10"> Registro de um novo Produto </div>
    <div class="col-2">
        @Html.ActionLink("Register New", "Cadastro", "Produto", new { area = "" }, new { @class = "nav-link btn btn-info" })
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>SKU</th>
                <th>Descrição</th>
                <th>Fabricante</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var produto in Model)
            {
                <tr>
                    <td>@produto.SKU</td>
                    <td>@produto.Descricao</td>
                    <td>@produto.Fabricante</td>
                </tr>
            }
        </tbody>
    </table>

</div>

MVC5.APP.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Produto", "Index", "Produto", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Web e-commerce Demo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Produto")
    @RenderSection("scripts", required: false)
</body>
</html>